### ISSUE TITLE
add image credits to information panel

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#104]
for now, I think we should add an EOL link/image credit to the information panels. see example from [invision](https://projects.invisionapp.com/share/JSQ7MXBECBA#/screens/350486676):

![image credit](https://user-images.githubusercontent.com/22624609/58122576-c758d080-7bbe-11e9-88b5-ca0c1c0729a6.png)

**Comment by Cdower** [comment]
https://storage.googleapis.com/public-tree-map/data/trees/10914721.json

**Comment by emillipede** [comment]
I'll think about how to write out the author name given the weirdness in the data from EOL.org

**Comment by Cdower** [comment]
Here's what it looks like now, I haven't found any trees with authors that wrap around but it should just force a new line.

**Comment by Cdower** [comment]
it loses padding on when it wraps around and I don't love that.

**Comment by emillipede** [comment]
thanks @Cdower I agree

I think the text size looks a little big, the background opacity is maybe too dark, too

Since the text running across the full width of the image is hard to read, what do you think about dropping the irregular credit names to just post "image via [eol.org](https://eol.org/pages/47154753/media)" (with the underlined URL linking to the species' media page)?

I think it'll also be easier to read the text and see the image if the credit is locked to the bottom left corner. Please let me know how that sounds to you

**Comment by emillipede** [comment]
one more thought/question @Cdower 

the urban forest task force asked me if we could switch the use selecTree as the site's source for images (we'd still need some image credit, just to a different site). 

the task force chair tried to contact the professor who helps run selecTree but didn't get anywhere. a long time ago, we talked about scraping the site for images. how does that sound to you? if we go that way, I think I ought to set up a new google cloud account
