### ISSUE TITLE
remove close button from tree name popup

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#120]
users can't click the "x" close button that appears in the popup, it's useless/annoying to display

popup formatting options documented [here](https://leafletjs.com/reference-1.5.0.html#popup-closebutton)

![Screen Shot 2019-06-28 at 11 55 47 PM](https://user-images.githubusercontent.com/22624609/60380806-65328d00-9a00-11e9-8cd5-dd19f65046cb.png)

**Comment by manuelizo** [comment]
I found the solution. Assign it to me and I'll do the PR tonight :smile:

**Comment by manuelizo** [comment]
I've just done the PR, waiting for someone who can merge.

**Comment by emillipede** [comment]
thank you so much @manuelizo I'll take a look! 

we love getting new people involved - how did you discover the project?

sorry for the delay in reply, we're in california and today is a holiday

**Comment by manuelizo** [comment]
To be honest @emillipede, I don't remember how I found this repo at all, but I'm interested in everything related to Open Source, Open Data from cities and this kind of things.

I'll try to help to this project as much as possible!

See ya ☺️

**Comment by emillipede** [comment]
thanks @manuelizo, that's awesome! we're happy to have help :slightly_smiling_face: 

if you'd like, you're welcome to join our informal [slack channel](https://hackforla.slack.com/messages/C9UU5KKAA/) (through Hack for LA, the local chapter of Code for America). you're also of course welcome to participate without joining slack! 

please let me know if I can answer any questions about the project or the open datasets involved

thanks again!

**Comment by manuelizo** [comment]
@emillipede sorry for offtopic here, but could you invite me into the slack channel? my email is: mlizot9@gmail.com
