### ISSUE TITLE
Create container for side bar information and filters

### ISSUE THREAD

**Issue by Reltre** [Public-Tree-Map/public-tree-map#14]
This component is a wrapper for two views which we want to show the user.  This component should be rendered alongside the map component on the right side. 

To complete this task, that doesn't have to be simulated though, just make this component in isolation. All components will be rendered together in `main` to display the entire application later on as a separate task.

[Samo tree map - updated 5 july 2018.pdf](https://github.com/emillipede/street-tree-map/files/2237541/Samo.tree.map.-.updated.5.july.2018.pdf)

1. General View
2. Tree View

**Comment by acostajake** [comment]
Submitting a PR for the navbar containing Heatmap, Filters, Meet the Locals. No functionality yet. I used styled-components and Grid, as well as Bootstrap for the buttons.

**Comment by emillipede** [comment]
pull request = #19

**Comment by emillipede** [comment]
attributes to color by:

- native/exotic species status
- invasive status
- conversation status (IUCN)
- irrigation requirements
- when they’ll be next pruned
- shade production
- taxonomic information
- plant family
- species
- genus (suggested by Peter)
- location - distance from specified address
- planting
- tree removals (TBD if this field is OK with Peter and Matthew)
- trunk diameter
- height

link to google sheet: https://docs.google.com/spreadsheets/d/1a8Wuipc_6rZYdlxCBvhHHumdDx-UCk8krfG8urXXClw/edit#gid=133444325
