### ISSUE TITLE
Create Container For Map Statistics

### ISSUE THREAD

**Issue by Reltre** [Public-Tree-Map/public-tree-map#15]
We want to display pertinent statistics depending on if a user has selected a tree or is viewing a part of the map. But first, we want the structure in place. Let's create a container to hold and accept relevant data. This task is for the subview just below the map.

Consult the following mockup for a reference. This task is for building the bottom bar that displays
[Samo tree map - updated 5 july 2018.pdf](https://github.com/emillipede/street-tree-map/files/2237546/Samo.tree.map.-.updated.5.july.2018.pdf)
 tree related information.

**Comment by emillipede** [comment]
pull request = #19
