### ISSUE TITLE
add (family select2 filter and) color keys to select2 filters

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#172]
for select2 filter:

- add color markers next to each species name, so that users can see which color corresponds to it
- allow users to only select one species at a time (I can split this part into another issue)

it'll be helpful for users to see which colors are associated with each species, something like the colored circles in this example (from the unfortunately closed source [NYC map](https://tree-map.nycgovparks.org/)) 
![Screen Shot 2019-10-07 at 11 10 06 AM](https://user-images.githubusercontent.com/22624609/66337287-bbfb0d00-e8f3-11e9-8a0a-73cdca22bb6f.png)

on the site now, the coloring in each "group by" category can be assigned by species - within a single species, there's no variation in the map markers' colors. if a user switches from grouping points by species to grouping them by CA native or endangered, the colors in the select2 bar should correspond to the re-colored map markers.

right now, there's no select2 search bar to filter by family (though users can group the points by family). if/how we'll incorporate it is TBD

**Comment by AkaXaphion** [comment]
am I okay to take this? is it separate from what's happening with #76 ?

I'm assuming this addresses grouping by species/family by having colored dots within the select2 dropdown options and selections

**Comment by emillipede** [comment]
thanks @AkaXaphion, you're more than welcome to go for it! this issue is separate from #76 (we haven't resolved how to add legends). i've made a couple of updates to the description, to reflect the current site. there's a little overlap #200, since that issue also involves the current select2 species search bar. if you have any questions, please let me know

thanks again!
