### ISSUE TITLE
reformat close buttons

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#186]
in desktop view, the sidebar close button does not match the zeplin

example screenshots from zeplin

in sidebar (over image):
![Screen Shot 2019-10-14 at 8 34 26 PM](https://user-images.githubusercontent.com/22624609/66798196-17b03200-eec2-11e9-8031-5f774798f6d5.png)

in mini sidebar:
![Screen Shot 2019-10-14 at 8 34 12 PM](https://user-images.githubusercontent.com/22624609/66798197-17b03200-eec2-11e9-8195-86d9833be9e3.png)

in mobile view, the close button in the mini-sidebar gets stuck under certain species names
![Screen Shot 2019-10-14 at 9 51 03 PM](https://user-images.githubusercontent.com/22624609/66801114-c8bbca00-eecc-11e9-964f-1f818aa5c020.png)

**Comment by isabelle-wagenvoord** [comment]
Hi, can I work on this?

**Comment by emillipede** [comment]
thank you @isabelle-wagenvoord go for it! https://www.w3schools.com/cssref/css_units.asp
