### ISSUE TITLE
improve mobile display preview window

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#244]
as a:
mobile user

when I:
view the mini information window

I want to:
see the relevant content, including "View Details" button (nothing cropped out of the window)

- the bottom of the page is also cropped on some devices. in some cases, the species photo and "view details" button are partially obscured (on some devices, the button isn't visible at all)
- on other devices, the "View Details" button appears very small - @sourcediz suggests making it responsive. maybe the whole preview window should be made responsive
  - with some longer species names, the close button and the species name overlap (see #186 for close button formatting)

note: 
- the issues with toolbar buttons are documented in #247

#### zeplin:
![Screen Shot 2019-09-23 at 11 31 05 PM](https://user-images.githubusercontent.com/22624609/65487037-d98f9780-de5a-11e9-9df4-0ec2cacbf181.png)

#### current website (on small iphone SE):
- preview window with one line species name:
![Image from iOS (2)](https://user-images.githubusercontent.com/22624609/68430081-4a1d1a00-0164-11ea-8bc8-6ca42ba697ff.png)

- preview window with two line species name (view deatils button not visible):  ![Image from iOS](https://user-images.githubusercontent.com/22624609/68430085-4ab5b080-0164-11ea-92bb-0d36c365ccce.png)
- same window, just scrolled down
![Image from iOS (1)](https://user-images.githubusercontent.com/22624609/68430083-4a1d1a00-0164-11ea-872d-68118ac9dd74.png)

**Comment by isabelle-wagenvoord** [comment]
Hi emily,
Can I work on this?

**Comment by emillipede** [comment]
hi @isabelle-wagenvoord! this issue comes in part from a suggestion by @sourcediz, so I just want to make sure they're not already at work on it.

@sourcediz, have you started on this issue? if so, would you like to collaborate with @isabelle-wagenvoord? if not, do you have any recommendations for Isabelle?

**Comment by emillipede** [comment]
resolved by #251 thank you @isabelle-wagenvoord!
