### ISSUE TITLE
browser problems

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#246]
the site doesn't seem to work in firefox

**Comment by isabelle-wagenvoord** [comment]
hi emily,
i took a look at the website using firefox, and it seems to work fine okay. does this have to do with a specific version of firefox?

**Comment by emillipede** [comment]
hi @isabelle-wagenvoord, you're right! thank you for taking a look at it, I'm sorry for the false alarm.

I was able to reproduce the problem on my computer when I filed the issue, but now the site seems fine on firefox.
