### ISSUE TITLE
List of known tasks

### ISSUE THREAD

**Issue by Reltre** [Public-Tree-Map/public-tree-map#25]
#### Frontend

- Create components for *single tree* view. These should nest in the statsContainer and navContainer.
- Create components for *general* view. These should nest in the statsContainer and navContainer. 
- - in *general* view (ie no tree is selected), filters appear in the a navigation bar, and the sidebar will display explanatory/introductory text and maybe a 'meet the locals' intro filter/story
- ""Container components do too much. They should hold child components and pass down data, depending on if you're looking at a single tree or the entire map. 
- Leaflet component doesn't work, it just shows random data. The zoom functionality is broken as well.
- A new component for holding filters based on the updated mockup needs to be added to the App component and also, well, just created.
**See [mockups](https://projects.invisionapp.com/share/A2NSKX4734Y#/screens) for more info there: **

#### Backend

- The computation for what data to display within a certain radius given what is being viewed needs to be figured out.
- Move database from sqlite to postgres
- Update models in sqlalchemy
- Ingest/query data from SM open data portal - trees inventory - dataset on regular schedule

**Comment by Reltre** [comment]
Feel free to add comments here if anyone has other ideas to add.

**Comment by emillipede** [comment]
- Retrieve species imagery from EOL API
- Retrieve street view imagery from google API

**Comment by emillipede** [comment]
DB
- Data into DB (postGIS needed when pending city pruning data added to DB)
- - From CSV
- - From SHP / GeoJSON
- Clean
- - validate species/families
- Join keys
- - Define, name (species names)
- - Make sure they work
- Backend aggregation for map zooms?
Design 
 - Build interactive filters into sidebar panel
Front end
- Basic filters
- Translate ALL CAPS to nice case
- Autocaching in graphQL
- Cluster / heat-mapping ? (or backend aggregation)
- Query APIs
- - EOL for species image
- - Google street view API for street image
Pending data
- Canopy tree library attributes
- City planting 
- City pruning
- City replacement species
- iTree tools
