### ISSUE TITLE
update add to any

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#253]
addtoany warning from Chrome:

"A cookie associated with a cross-site resource at http://addtoany.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`."

**Comment by mrtmrt233** [comment]
Is this issue still present? If so can you give detailed steps on how to reproduce it?

**Comment by emillipede** [comment]
I don't see this warning anymore, thank you for checking on it @mrtmrt233. late last year, I always saw it in developer tools
