### ISSUE TITLE
add "last updated: date / time" to sidebar

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#257]
at the bottom of the sidebar, add a field that displays "data last updated: day month year" date for users

the date should reflect the last time circle CI successfully ran (ie the last time the pipeline updated from the city's dataset)

**Comment by theswerd** [comment]
Can I work on this?

**Comment by emillipede** [comment]
sure, thank you @theswerd go for it! 

the date should reflect the last time circle CI successfully ran (ie the last time the pipeline updated from the city's dataset). please add the field at the bottom of the sidebar. 

thanks again!

**Comment by emillipede** [comment]
hey @theswerd! would you still like to work on this issue? if not, no problem
