### ISSUE TITLE
fix marker size bug

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#272]
when a user has selected a tree marker and then switches from one view to another (eg from "endangered" to "family"), the selected marker expands again in size, and then if a user selects another marker, the first marker doesn't ever return to regular size

selects marker:
![Screen Shot 2020-04-28 at 3 54 29 PM](https://user-images.githubusercontent.com/22624609/80545690-cef52d80-8968-11ea-9e7d-93b2e77a9a5a.png)

changes view, marker expands again:
![Screen Shot 2020-04-28 at 3 54 59 PM](https://user-images.githubusercontent.com/22624609/80545692-d1578780-8968-11ea-84c0-22772a48e269.png)

changes marker, previously expanded marker reduces in size (but not all the way to regular size):
![Screen Shot 2020-04-28 at 3 55 14 PM](https://user-images.githubusercontent.com/22624609/80545694-d1f01e00-8968-11ea-83eb-2f6170046dbf.png)

**Comment by mrtmrt233** [comment]
I noticed this the other day when playing with a few things. 

Looks like it had something to do with the way the color switch function and the marker click event are implemented: 
-when clicked on a view, a new set of color was passed to the map and the redraw function was called to re-render every marker. 
-when a marker was clicked, it was re-rendered to a larger size, and resume to regular size when a different marker was clicked
Seems like the entire redraw logic didn't deal with already enlarged marker correctly. There could be multiple ways to patch this quickly, but I might need to play with a few more things to understand the whole call chain. Or maybe someone else could look into this?
