### ISSUE TITLE
resolve location feature bug

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#278]
there's a problem with the GPS location and or bounding box.

the "outside SM" error appears when users are within the city

last night when I went for a walk, I was at [this corner](https://www.google.com/maps/place/34%C2%B002'04.8%22N+118%C2%B029'45.6%22W/@34.034667,-118.4981817,17z/data=!3m1!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d34.0346666!4d-118.4959928). I tried to test the location feature, and the message popped up
![515C2FDD-E743-4F2E-B3B9-6A9CAFCB7EB6](https://user-images.githubusercontent.com/22624609/81332968-b49e0c80-9058-11ea-93ab-6c83e2db5d0e.png)

i also tried the algolia location feature, which seems to constantly refresh. that doesn't allow users to move/adjust the map view. (the algolia one also doesn't yet drop a marker onto the map, which is a requested feature).

I'd like to offer (just) one functional option - either the location feature within the algolia address bar (or the location button). in either case, the design recommends putting the icon in the toolbar.

we could disable the bounding box, and I can test it again (to see where the map locates me). I'd like to know if gps function of the button isn't glitchy (it seems to work around my apartment), or if there's a problem with the bounding box.

**Comment by mrtmrt233** [comment]
So I've poked around a bit, and looks like the address bar is working correctly. 

Location button is not working with all browsers in iOS (tried safari, firefox, chrome), but no issue on desktop with mobile sized window. I have some ideas to try out.

**Comment by emillipede** [comment]
Thank you @mrtmrt233 ! 

The location button within the address bar (the one that's part of algolia places) doesn't drop a marker to indicate and follow the user's location. The location button at the bottom right corner does drop a marker. Do you think it's possible to add the user marker feature to the algolia location button?

**Comment by emillipede** [comment]
@cajaks2 suggests removing the location/bounding box/pop up. 

how to remove the location icon from algolia places bar?

**Comment by mrtmrt233** [comment]
- remove pin icon from address bar
    can be done, I think. 

- remove bounding box
    not sure if I understand this. Does this mean removing the "outside santa monica" related logics entirely?

@emillipede @cajaks2

**Comment by emillipede** [comment]
thank you for following up @mrtmrt233 !

address bar:
- the current address bar and pin are documented in [geolocation.js](https://github.com/Public-Tree-Map/public-tree-map/blob/ad00ecf5f973a7899dbc7cb9c44367d81a3a1975/public/js/Geolocation.js) but the location button is in [map.js](https://github.com/Public-Tree-Map/public-tree-map/blob/ad00ecf5f973a7899dbc7cb9c44367d81a3a1975/public/js/Map.js). I think that it's possible to remove the pin element. it'd be optimal if the location icon/pin in the address bar worked the way the button (at the bottom R of the screen) does/replaced the button. do you think that is possible? would that change require a lot of work?

- side notes:
- I don't know that the code split up in map and geolocation files makes sense - two different people (at separate times) made those contributions, so the file set-up is really an artifact of that. do you think they belong in the same file? 
- the address bar is imperfect (algolia doesn't consider street numbers, and the drop down can be hard to see on a mobile device) but I think it's better than the free alternatives, decent enough to keep for now.

bounding box:
- the change you made does seem like it addressed the problem I had in the neighborhood at the north end of the city. I'm going to merge it. thank you! @cajaks2 suggested removing the bounds for a couple of reasons (cooper feel free to clarify!), I don't think the concerns urgent
