### ISSUE TITLE
evaluate street view options

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#281]
**AS A/AN**:
user

**WHEN I**:
view a tree on the map

**I WANT TO**:
see street view imagery of that tree as it exists in the city. street views aren't available for the the almost 6,000 trees in and around city parks. however, I think it's still a feature worth exploring

these street view panels could go in the sidebar in addition to the EOL images (maybe further down in the sidebar)

google offers free access to their maps [street view data](https://developers.google.com/maps/documentation/javascript/examples/streetview-service), up to $200 in monthly usage. I don't think we'll exceed that anytime soon

**Comment by mrtmrt233** [comment]
I looked into this a while back, and apparently using google street view with a non-google map such as leaflet is in violation of their [terms of service](https://cloud.google.com/maps-platform/terms/). Normally this wouldn't be a realistic problem in a small app but I don't know if doing this for a government backed app is a good idea?

> 3.2.3 Restrictions Against Misusing the Services.
(e) No Use With Non-Google Maps. To avoid quality issues and/or brand confusion, Customer will not use the Google Maps Core Services with or near a non-Google Map in a Customer Application. For example, Customer will not (i) display or use Places content on a non-Google map, **(ii) display Street View imagery and non-Google maps on the same screen**, or (iii) link a Google Map to non-Google Maps content or a non-Google map.

**Comment by emillipede** [comment]
Hi @mrtmrt233 thank you for investigating this issue. Since we're a small independent project, I think street view is worth a try right now. 

For mobile users (the majority of expected users), the street view imagery will automatically appear in a separate screen - the sidebar and map aren't visible at the same time. To comply with the terms for users on desktop browsers, we could display street view imagery only in the full window.

How does that sound to you?
