### ISSUE TITLE
Update models info and schemas

### ISSUE THREAD

**Issue by Reltre** [Public-Tree-Map/public-tree-map#29]
The SQLAlchemy models are out of date. The fields listed in our schema file should match what we want to have in our database, but it doesn't at the moment.

Update the current schema and add to it to match the database tables we want to track in our database.
Note, this is blocked by the normalization issue #16 .

**Comment by emillipede** [comment]
@Reltre is this issue still blocked?

**Comment by Reltre** [comment]
@emillipede Nope, this issue isn't blocked. Hmm, looking over the current state of the database, it seems that this issue was also addressed as well. There is one thing that I recommend, and that is to change the family botanical name column in the species schema. This seems strange to me, as it is specified as a foreign.

We can probably remove that from the table and have something like `family_id` instead. If we need th family name, then we can grab it with a join. The same thing can be said for `name_botanical` in the `Tree` schema.

**Comment by emillipede** [comment]
thanks @Reltre sounds good to me. I'm glad you noticed that issue. the draft schemas did keep the family names out of the species + tree tables tables. we'll need to display the family names, but we I think ought to store the information in the separate family table.
