### ISSUE TITLE
add publictreemap.org

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#297]
a little while ago, I got publictreemap.org from google domains. the site currently updates surge and github pages. I'd like to add publictreemap.org (via github pages?)

github pages option suggested by @thekaveman:
- add "gh-pages" branch
- set up github actions to, with each push to master, duplicate the updated contents of the public folder to the "gh-pages" branch (and override the existing branch)

see also [#78](https://github.com/Public-Tree-Map/public-tree-map-data-pipeline/issues/78) for another possible data pipeline-related application of github actions
- github pages offers unlimited minutes (maybe), which would allow for processing additional tree datasets

**Comment by mrtmrt233** [comment]
https://surge.sh/help/adding-a-custom-domain

documentation on how to do this with surge.sh
