### ISSUE TITLE
More resources about tree data protocols

### ISSUE THREAD

**Issue by matikin9** [Public-Tree-Map/public-tree-map#4]
https://urbanforestry.indiana.edu/doc/publications/2015-need-to-standardize.pdf
http://www.urbantreegrowth.org/field-guide.html

**Comment by emillipede** [comment]
Awesome. Thank you, Nina! I added these PDFs to the list of links at the bottom of the readme.

I don't think that data and reporting are a big part of the SM urban forest master plan. I wonder if West Coast Arborists, the company that contracts with SM, follows a specific workflow.

Here's a guideline from the city of Atlanta 2015: 
https://www.atlantaga.gov/home/showdocument?id=20151
