### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#52]
(now split into separate issues)

- allow user to slide up on mini toolbar to open full sidebar (gesture detection)
- mobile layout doesn't work if user turns mobile device horizontal (show warning?)
- in mini sidebar 
       - window, image, and map do not resize together the same way
      - close button can overlap with species name
- Double scrollbar in full-screen sidebar
- top and bottom of the page are hidden/cropped in some mobile browsers (top toolbar labels (group by, zoom to address, and "view details" button are sometimes not visible) (#227)

- apply formatting (mini sidebar, view details button) to vacant sites/asphalted wells etc (#201)
- close button styling (see #186)
- how to select a tree on a touch screen? 
      - increase touch radius (markers are hard to select)
  ~~- works on some mobile phones~~
  ~~- on some phones, only activates hover (vs opening mini sidebar)~~ (see #223)
- street address doesn't display in mini sidebar (#226)
- toolbar buttons look a little off (too big? weird borders?) (#227)

**Comment by manuelizo** [comment]
Hey!

I have just tried in mobile resolution and it's kinda difficult..maybe the info panel could be hide and show it when you press a little button in a corner saying "more info" or something like that.

I could try to make something if you want and solve this problem.

In this case:
![image](https://user-images.githubusercontent.com/18089789/60685144-c72c4000-9ea1-11e9-95d1-23d8a92f7f0b.png) tablet resolution has the same problem.

How should we fixed it? Is it important? 😄

**Comment by emillipede** [comment]
Hi @manuelizo ! Thank you for taking a look at this issue. I think it'll be important for users to be able to interact with the map on mobile devices. 

A solution we've discussed is allowing mobile users to either see the map or the information panel, not both at once. There's a [tree map](https://tree-map.nycgovparks.org/) developed for the city of New York that takes this approach.

Since the sidebar dimensions and the filter bars aren't yet finalized, it may make sense to wait on sorting out this problem.
