### ISSUE TITLE
Where To Host WebApp

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [Public-Tree-Map/public-tree-map#55]
1. We can host the webapp at GitHub pages or on a AWS type cloud server.
2. We will need to host the cron job on a server (not GitHub pages).
3. We need a server location (not GitHub) for Credentials and Keys.

**Comment by greysonp** [comment]
2. Looking at Google App Engine cron jobs and Google Cloud Scheduler.

**Comment by greysonp** [comment]
App is hosted on surge.sh. The data is hosted on GCS.
