### ISSUE TITLE
link to Santa Monica Works webform to report tree problems

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map#63]
**as a:** 
user

**when I:**
have a question about or notice a problem with a city tree or vacant site

**I want to:**
easily communicate the question or concern to city staff

interim plan:
add a section to the bottom of the tree and vacant sidebars in this format:
![Screen Shot 2020-04-28 at 9 03 43 PM](https://user-images.githubusercontent.com/22624609/80559843-cebe5780-8993-11ea-835a-2ab19f2861e8.png)

with this text: 

- Report an Issue
- Notice an issue with this tree? Notify Santa Monica's Public Landscape Manager via **Santa Monica Works** ("Santa Monica Works" links to ["Trees" topic area](https://user.govoutreach.com/santamonica/support.php?classificationId=30642&cmd=shell) within the "Problems & Repairs" section

future (not current) plans:
- the city-assigned tree ID and lat/long will be automatically copied to the user's clipboard (possible solution: https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f), but that might not be an option 
- a button will open an interface to allow users to directly submit reports to the city's works app's ["Trees" topic area](https://user.govoutreach.com/santamonica/support.php?classificationId=30642&cmd=shell) within the "Problems & Repairs" section, rather than direct users to the city's website (this integration with SM GO is on hold to explore how to address CORS server errors)

Note - users may need to create accounts in order to submit issues via the city's app

**Comment by theswerd** [comment]
Using the http library as http

This http call will allow you to fill in the form with your own data, without opening the window.
```
http.post(
        "https://user.govoutreach.com/santamonica/support.php?cmd=newcase",
        body: {
          "classificationId":"30642",
          "locationCoord":long+", "+lat,
          "location":location,
          "treeIssue": treeIssue,
          "description": description,
        //Compented is optional
        //  "firstName":"",
        //  "lastName": "",
        //  "email":"",
        //  "phone":"",
        //  "altPhone":"",
        //  "address":"",
        //  "city":"santa monica",
        //  "state":"California",
        //  "zip":"90405"
        }
        ),
   
```

**Comment by emillipede** [comment]
(written in dart with http library) thank you @theswerd !

**Comment by emillipede** [comment]
hey @theswerd and @thekaveman 

as an alternate solution to CORS problem, what about using a the "report" button to push to a queue that triggers a bot to complete the city form? this [google tutorial](https://cloud.google.com/functions/docs/tutorials/pubsub) makes it look possible and possibly free

please let me know what you think

**Comment by mrtmrt233** [comment]
checking in: are we not doing the email thing(as shown in screenshot in the issue) for sure? it'd be pretty easy to set up a mailto link that fills in specific tree/site info (locations etc.) for users.

**Comment by emillipede** [comment]
thanks for following up about this difference, @mrtmrt233 

the city landscape staff asked us to link to the web form. city employees are supposed to try to direct all community interactions to this Santa Monica Works interface, rather than starting them over email (so they can track metrics :/ )
